
  CREATE TABLE "U27"."FUNKCJA" 
   (	"FUNKCJA" VARCHAR2(13 BYTE) NOT NULL ENABLE, 
	"IDENTYFIKATOR" NUMBER(10,0) NOT NULL ENABLE, 
	 CONSTRAINT "FUNKCJA_PK" PRIMARY KEY ("IDENTYFIKATOR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

  CREATE OR REPLACE TRIGGER "U27"."FUNKCJA_PK" 
 BEFORE INSERT ON FUNKCJA
 FOR EACH ROW
    BEGIN
      :new.IDENTYFIKATOR:=FUNKCJA_AI.nextval;
    END;
/
ALTER TRIGGER "U27"."FUNKCJA_PK" ENABLE;
 

  CREATE TABLE "U27"."OFERTYSPRZEDAZ" 
   (	"VIN" VARCHAR2(20 BYTE), 
	"OSOBAID" NUMBER(10,0), 
	 CONSTRAINT "OFERTY_FK" FOREIGN KEY ("OSOBAID")
	  REFERENCES "U27"."TKLIENCI" ("IDOSOBA") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

  CREATE OR REPLACE TRIGGER "U27"."OFERTYSPRZEDAZ_PK" 
 BEFORE INSERT ON OFERTYSPRZEDAZ
 FOR EACH ROW
    BEGIN
      :new.VIN:=OFERTYSPRZEDAZ_SEQ.nextval;
    END;


  CREATE TABLE "U27"."SPRZEDANE" 
   (	"ID_TRANSAKCJI" NUMBER(10,0) NOT NULL ENABLE, 
	"VIN" VARCHAR2(20 BYTE), 
	"OSOBA_ID" NUMBER, 
	"DATA_SPRZEDAZY" DATE, 
	 CONSTRAINT "SPRZEDANE_PK" PRIMARY KEY ("ID_TRANSAKCJI")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "ODOBA_FK" FOREIGN KEY ("OSOBA_ID")
	  REFERENCES "U27"."TKLIENCI" ("IDOSOBA") ENABLE, 
	 CONSTRAINT "VIN_FK" FOREIGN KEY ("VIN")
	  REFERENCES "U27"."TSAMOCHOD" ("VIN") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

  CREATE OR REPLACE TRIGGER "U27"."PRZEN_AUTO_TG" 
 BEFORE INSERT ON SPRZEDANE
 FOR EACH ROW
    BEGIN
      :new.ID_TRANSAKCJI:=SPRZEDANE_SEQ.nextval;
    END;
/
ALTER TRIGGER "U27"."PRZEN_AUTO_TG" ENABLE;
 

  CREATE TABLE "U27"."TKLIENCI" 
   (	"IDOSOBA" NUMBER(5,0) NOT NULL ENABLE, 
	"IMIE" VARCHAR2(9 BYTE), 
	"NAZWISKO" VARCHAR2(12 BYTE), 
	"DATAURODZENIA" DATE, 
	"PESEL" NUMBER(11,0), 
	"MIEJSCOWOSC" VARCHAR2(10 CHAR), 
	"ULICA" VARCHAR2(16 BYTE), 
	"NUMERDOMU" NUMBER(3,0), 
	"NUMERMIESZKANIA" NUMBER(3,0), 
	"NUMERTELEFONU" VARCHAR2(20 BYTE), 
	"KODPOCZTOWY" VARCHAR2(20 BYTE), 
	"IDENTYFIKACJA" NUMBER(10,0) NOT NULL ENABLE, 
	 CONSTRAINT "PK" PRIMARY KEY ("IDOSOBA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "TKLIENCI_FK" FOREIGN KEY ("IDENTYFIKACJA")
	  REFERENCES "U27"."FUNKCJA" ("IDENTYFIKATOR") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

  CREATE OR REPLACE TRIGGER "U27"."TKLIENCI_PK" 
 BEFORE INSERT ON TKLIENCI
 FOR EACH ROW
    BEGIN
      :new.IDOSOBA:=TKLIENCI_SEQ.nextval;
    END;


/
ALTER TRIGGER "U27"."TKLIENCI_PK" ENABLE;
 

  CREATE TABLE "U27"."TMIEJSCOWOSC" 
   (	"IDENTYFIKATOR" VARCHAR2(1 BYTE), 
	"MIEJSCOWOSC" VARCHAR2(10 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

  CREATE TABLE "U27"."TSAMOCHOD" 
   (	"IDENTYFIKATOR" VARCHAR2(2 BYTE) NOT NULL ENABLE, 
	"MARKA" VARCHAR2(10 BYTE), 
	"MODEL" VARCHAR2(51 BYTE), 
	"ROK_PRODUKCJI" NUMBER(4,0), 
	"VIN" VARCHAR2(17 BYTE), 
	"KOLOR" VARCHAR2(9 BYTE), 
	"PRZEBIEG" NUMBER(6,0), 
	"POJEMNOSC_SKOKOWA" NUMBER(4,0), 
	"CENA" NUMBER(9,0), 
	"RODZAJ_POJAZDU" VARCHAR2(9 BYTE), 
	"RODZAJ_PALIWA" VARCHAR2(11 BYTE), 
	"STAN_TECHNICZNY" VARCHAR2(10 BYTE), 
	"RODZAJ_NADWOZIA" VARCHAR2(14 BYTE), 
	"SILNIK" VARCHAR2(14 BYTE), 
	 CONSTRAINT "PKVIN" PRIMARY KEY ("VIN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 
